# Generated by Django 2.2.6 on 2019-11-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_page_lock", "0002_auto_20170605_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasepagelockmodel",
            name="tab_counter",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
