# Generated by Django 3.2.16 on 2022-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_page_lock", "0003_databasepagelockmodel_tab_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasepagelockmodel",
            name="last_checked",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
